name: Terraform QA Only

on:
  push:
    paths:
      - 'environments/qa/**'

jobs:
  terraform-qa:
    name: Terraform Plan & Apply (qa)
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      
    defaults:
      run:
        working-directory: ./environments/qa

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var-file="qa.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
